# Generated by Django 6.0 on 2025-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('user', 'User'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('vendor', 'Vendor'), ('delivery', 'Delivery')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer Not To Say')], max_length=30)),
                ('delivery_address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('business_license', models.CharField(blank=True, max_length=30)),
                ('pharmacy_name', models.CharField(blank=True, max_length=150)),
                ('business_address', models.TextField(blank=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=20)),
                ('id_proof_number', models.CharField(blank=True, max_length=30)),
                ('id_proof_type', models.CharField(blank=True, max_length=20)),
                ('medical_license', models.CharField(blank=True, max_length=30)),
                ('specialization', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('clinic_address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
