# Generated by Django 4.2.7 on 2025-12-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_city_userprofile_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
