# Generated by Django 4.2.7 on 2025-12-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pincode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='apartment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
