# Generated by Django 4.2.7 on 2025-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
