# Generated by Django 4.2.7 on 2025-12-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('driving_license_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('aadhar_front', models.ImageField(upload_to='delivery/aadhar/')),
                ('aadhar_back', models.ImageField(upload_to='delivery/aadhar/')),
                ('pan_card', models.ImageField(upload_to='delivery/pan/')),
                ('license_front', models.ImageField(upload_to='delivery/license/')),
                ('license_back', models.ImageField(upload_to='delivery/license/')),
                ('vehicle_rc', models.ImageField(upload_to='delivery/vehicle/')),
                ('live_photo', models.ImageField(upload_to='delivery/selfie/')),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_aadhar_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
