# Generated by Django 4.2.7 on 2025-12-15 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypartner',
            name='aadhar_back',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/aadhar/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='aadhar_front',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/aadhar/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='license_back',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/license/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='license_front',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/license/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='live_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/selfie/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/pan/'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='vehicle_rc',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/vehicle/'),
        ),
    ]
