# Generated by Django 4.2.7 on 2025-12-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliverypartner_aadhar_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
