# Generated by Django 4.2.7 on 2025-12-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormedicine',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendormedicine',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
